#######################################################################################
#######################################################################################
#######################################################################################
#####                                                                             #####
#####                 SyncSpawners (Synchronous Spawners)                         #####
#####                  Created By FroggyKnight & Driftay                          #####
#####                            Fixed By Ryder                                   #####
#####                                                                             #####
#######################################################################################
#######################################################################################
#######################################################################################

#Don't be intimidated by this single line in the config, this plugin was designed for complete performance, and is unique to all servers!


#Time In Seconds For Spawner Sync
spawn-time: 10

