#######################################################################################
#######################################################################################
#######################################################################################
#####                                                                             #####
#####                  dSpawners (Synchronous Spawners)                           #####
#####                 Created By FroggyKnight & Driftay                           #####
#####                                                                             #####
#######################################################################################
#######################################################################################
#######################################################################################


#Time In Seconds For Spawner Sync
spawn-time: 10

