name: SyncSpawners
main: me.driftay.spawners.SyncSpawners
version: ${project.version}
authors:
  - Driftay
  - FroggyKnight
commands:
  syncspawners:
    description: Default Command for SyncSpawners

permissions:
  syncspawners.admin:
    description: Administration Rights To SyncSpawners